version: '3.9'

services:
  app:
    image: 'zbyna64/new-coordinator'
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile.jvm
    container_name: coordinator
    depends_on:
      - db
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/db
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=postgres

    ports:
      - "8080:8080"
    networks:
      - quarkus

  db:
    image: 'postgres:14.9-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    ports:
      -  "5432:5432"
    networks:
      - quarkus

networks:
  quarkus:
    driver: bridge